version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: /bin/bash -c "chmod 777 /srv/jekyll && jekyll serve --force_polling"
    tty: true
    ports:
      - 3000:4000
      - 3010:35729
    volumes:
      - "./:/srv/jekyll"
